In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('.csv')

FileNotFoundError: [Errno 2] File /content/datasets_596958_1073629_Placement_Data_Full_Class.csv does not exist: '/content/datasets_596958_1073629_Placement_Data_Full_Class.csv'

In [ ]:
data

##Separate Features and Target

In [ ]:
x = data.drop(['status','salary'], axis=1)
y = data.iloc[:, -2]

In [ ]:
x

In [ ]:
y

In [ ]:
x = data.drop(['status','salary'], axis=1).values

In [ ]:
x

In [ ]:
y = data.iloc[:, -2].values

In [ ]:
y

##One Hot Encoder


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
tab = pd.DataFrame(data=x)

In [ ]:
tab

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
tab = pd.DataFrame(data=x)

In [ ]:
tab

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
tab = pd.DataFrame(data=x)

In [ ]:
tab

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
tab = pd.DataFrame(data=x)

In [ ]:
tab

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [13])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
tab = pd.DataFrame(data=x)

In [ ]:
tab

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [16])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
tab = pd.DataFrame(data=x)

In [ ]:
tab

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [19])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(x))

In [ ]:
tab = pd.DataFrame(data=x)

In [ ]:
tab

##Splitting Data into Train and Test sets

In [ ]:
from sklearn.model_selection import train_test_split

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

NameError: name 'train_test_split' is not defined

In [4]:
x_train

NameError: name 'x_train' is not defined

In [5]:
y_train

NameError: name 'y_train' is not defined

##Label Encoder


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()

In [8]:
let = le.fit_transform(y_train)

NameError: name 'y_train' is not defined

In [ ]:
let

In [ ]:
les = le.fit_transform(y_test)

In [ ]:
les

##Standardization

In [50]:
from sklearn.preprocessing import StandardScaler

In [51]:
sc = StandardScaler()

In [52]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##Train on different algorithms

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [54]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel='rbf')

In [55]:
l_cla.fit(x_train, let)
k_cla.fit(x_train, let)
d_cla.fit(x_train, let)
r_cla.fit(x_train, let)
s_cla.fit(x_train, let)
ks_cla.fit(x_train, let)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [56]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [57]:
from sklearn.metrics import confusion_matrix

In [58]:
l_c = confusion_matrix(les, l_pred)
k_c = confusion_matrix(les, k_pred)
d_c = confusion_matrix(les, d_pred)
r_c = confusion_matrix(les, r_pred)
s_c = confusion_matrix(les, s_pred)
ks_c = confusion_matrix(les, ks_pred)

In [59]:
l_c

array([[11,  2],
       [ 2, 28]])

In [60]:
k_c

array([[ 4,  9],
       [ 2, 28]])

In [61]:
d_c

array([[11,  2],
       [ 6, 24]])

In [62]:
r_c

array([[11,  2],
       [ 2, 28]])

In [63]:
s_c

array([[11,  2],
       [ 2, 28]])

In [64]:
ks_c

array([[ 9,  4],
       [ 1, 29]])

In [65]:
from sklearn.metrics import accuracy_score

In [66]:
l_a = accuracy_score(les, l_pred)
k_a = accuracy_score(les, k_pred)
d_a = accuracy_score(les, d_pred)
r_a = accuracy_score(les, r_pred)
s_a = accuracy_score(les, s_pred)
ks_a = accuracy_score(les, ks_pred)

In [67]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(ks_a))

Logistic Regression: 0.9069767441860465
KNN: 0.7441860465116279
Decision Tree: 0.813953488372093
Random Forest: 0.9069767441860465
Linear SVC: 0.9069767441860465
Kernel SVC: 0.8837209302325582
